apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceapprincy-deployment
  labels:
    app: myinsuranceapprincy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myinsuranceapprincy
  template:
    metadata:
      labels:
        app: myinsuranceapprincy
    spec:
      containers:
      - name: myinsuranceapprincy
        image: myinsuranceapprincy:v8
        ports:
        - name: http
          containerPort: 5000